### ISSUE TITLE
ES5 or Nodejs Support?

### ISSUE THREAD

**Issue by silkyland** [StorePilot/coinify#3]
This repo is awesome but I try to import your package as a dependency to my NodeJS project using es5 or node module via require and it never support

`const coinify = require('coinify')`

and I got 

`export default class Coinify {
^^^^^^
SyntaxError: Unexpected token export`

**Comment by steffanhalv** [comment]
@silkyland It is Es6 syntax, you can load it using babel loader. Else you can contribute by making it es5 compatible /  create a minified version and create a pull request ;)

**Comment by steffanhalv** [comment]
I have to add some more currencies, so I can make it es5 compatible at the same time. Will also try to remove the constructor so it can be used at once.

**Comment by steffanhalv** [comment]
@silkyland Should now be fixed, import for ES5 from dist folder.

Ex. const coinify = require('coinify/dist/coinify')

0f5de89c0cba791669cf551c74a71c83e4dc12f9

**Comment by zimme** [comment]
How about setting `main` in `package.json` to the es5 version in `dist` and use `module` for the es6+ version?

**Comment by steffanhalv** [comment]
Sure, that would be better. I fix it next week :)

**Comment by steffanhalv** [comment]
d2395f1deb71d978e2bf68fabdb416427c704d93
